plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: 'cd workoutplanner && mvn versions:set -DnewVersion="${nextRelease.version}" -DgenerateBackupPoms=false -DprocessAllModules=true'
  - '@semantic-release/gitlab'
  - - '@semantic-release/git'
    - assets:
        - workoutplanner/pom.xml
        - workoutplanner/core/pom.xml
        - workoutplanner/fxui/pom.xml
        - workoutplanner/fxutil/pom.xml
        - CHANGELOG.md
      message: 'chore(release): bump ${nextRelease.version}'

branches:
  - 'main'
